<?php

/**
 * PluginsfDoctrineSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfDoctrineSlotTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfDoctrineSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfDoctrineSlot');
    }
}